### PR TITLE
Add empty startup_hook

### PR DESCRIPTION
**Pull request by harupiko**
Add 'startup_hook' that is required by dehydrated from commit  60583d3ef9a62712851adeb488c7b454dc36ccbf .

### CODE REVIEW

**Comment by myusuf3** [comment]
This fixes the issue.

**Review by vikrantrathore — COMMENTED** [review]
This change should be merged as it solved one of the issue I just raised.

**Comment by myusuf3** [comment]
@kappataumu please merge this.

**Comment by sylveon** [comment]
For those already having a local copy, you can use the following command to get this patch right now:

    git remote add startup-hook https://github.com/harupiko/letsencrypt-cloudflare-hook.git
    git pull startup-hook master

**Comment by kappataumu** [comment]
Thank you @harupiko and sorry for taking so long.

**Pull request merged**
